# Generated by Django 4.2 on 2023-04-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friendlyface", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="person",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="friendlyface.tag"
            ),
        ),
    ]
