# Generated by Django 4.2 on 2023-04-21 17:46

from django.db import migrations, models
import friendlyface.models


class Migration(migrations.Migration):
    dependencies = [
        ("friendlyface", "0003_rename_person_profile_user_alter_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                null=True, upload_to=friendlyface.models.profile_image_file_path
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
